### PR TITLE
Seedset protoclass

### PR DESCRIPTION
**Pull request by sjanssen2**
Adressing issue #16 : adding seedset functionality to last outstanding prototype function 'protoclass'

### CODE REVIEW

**Comment by sjanssen2** [comment]
@qiyunzhu ready for a review

**Review by qiyunzhu — APPROVED** [review]
Good job! @sjanssen2 The rationale is very clear. So the order of seeds is not important. The program just picks random one each time until all seeds are gone. Is that right?

**Comment by tkosciolek** [comment]
I cannot say that I understand this PR fully, but the code looks good!
@qiyunzhu I'm not able to merge, because I'm not a member of this project.

**Comment by qiyunzhu** [comment]
@tkosciol Thank you! The code is to let the prototype selection function take a pre-defined set of "seeds", which are guaranteed to be selected as prototypes. The remaining prototypes will be calculated based on them.

**Comment by sjanssen2** [comment]
Hi @qiyunzhu I never replied to your question. You are right: elements of the seedset are made prototypes in a random ordering until all are "consumed".
Since at least |seedset| elements will be returned as prototypes (even if the user set num_prototypes to a smaller number) the ordering should not matter.

**Pull request merged**
